# Generated by Django 5.1.1 on 2024-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_cursos_institucion_inscripcion_sede_cursos_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
