services:
  django:
    image: django_app
    container_name: django_app
    build:
      context: ./djangoApp
    ports:
      - "8000:8000"
    volumes:
      - ./djangoApp:/app
    command: >
      bash -c "./wait-for-it.sh mysql:3306 --timeout=60 --strict -- 
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - mysql

  react:
    container_name: react_app
    image: react_app
    build:
      context: ./reactApp
    volumes:
      - ./reactApp:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"  # Cambiado de 3307 a 3306 para consistencia
    environment:
      - MYSQL_ROOT_PASSWORD=kevinalpizar1998@PUTOamo
      - MYSQL_DATABASE=jdb
    volumes:
      - django_react_data:/var/lib/mysql  # Cambiado la ruta del volumen
      - ./dumps:/docker-entrypoint-initdb.d:ro

volumes:
  django_react_data: