# Generated by Django 5.1.1 on 2024-10-17 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_course_modality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='second_last_name',
        ),
    ]
