# Generated by Django 5.1.1 on 2024-10-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_enrollment_email_remove_enrollment_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
    ]
