# Generated by Django 5.1.1 on 2024-10-25 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
