# Generated by Django 5.1.1 on 2024-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_campus_latitude_campus_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
    ]
