# Generated by Django 5.1.1 on 2024-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_course_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
