# Generated by Django 5.1.1 on 2024-11-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10),
        ),
    ]
